name: Deploy HTML to Azure Web App

on:
  push:
    branches:
      - master   # or main, depending on your repo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Log in to Azure using OIDC (federated credentials)
      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # 3. Deploy static HTML files to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: josehtmldemo        # Replace with your Azure Web App name
          package: .                    # Deploy the root of the repo
