name: Deploy HTML to Azure Web App - josehtmldemo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7C33586803C443538C9812004C2E7E04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_808A9CE5191E4EE1BB93E4944A01DB7E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29035A053CA64AFFAD4ECC5F6E3C1EC4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'josehtmldemo'
          slot-name: 'Production'
          package: .
